live_config_reload = true

import = [
  "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[window]
padding.x = 10
padding.y = 10
blur = true
option_as_alt = "OnlyLeft"

[font]
normal.family = "FiraCode Nerd Font Mono"
size = 11

[selection]
save_to_clipboard = true

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "K", mods = "Command" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[colors]
transparent_background_colors = true

[keyboard]
bindings = [
  { key = "Return", mods = "Control", chars = "\u001b[13;5u" },
  { key = "Return", mods = "Shift", chars = "\u001b[13;2u" }
]
